Attendance/Attendance/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Attendance.Models
{
    [Table("Location")]
    public class Location : BaseEntity
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(500)]
        public string Name { get; set; }

        public string Description { get; set; }

        public virtual ICollection<EnglishClass> Classes { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}

Attendance/Attendance/ViewModels/Locations/CreateLocationVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Attendance.ViewModels
{
    public class CreateLocationVM
    {
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
}

Attendance/Attendance/ViewModels/Locations/DeleteLocationsVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Attendance.ViewModels
{
    public class DeleteLocationVM
    {
        public int Id { get; set; }
        [Display(Name = "Location")]
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Display(Name = "Date Created")]
        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public DateTimeOffset? DateCreated { get; set; }
        [Display(Name = "Date Updated")]
        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public DateTimeOffset? DateUpdated { get; set; }
        [Display(Name = "User Created")]
        public string UserCreated { get; set; }
        [Display(Name = "User Updated")]
        public string UserUpdated { get; set; }
    }
}

Attendance/Attendance/ViewModels/Locations/DetailsLocationVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Attendance.ViewModels 
{
    public class DetailsLocationVM 
    {
        public int Id { get; set; }
        [Display (Name = "Location")]
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Display(Name = "Date Created")]
        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public DateTimeOffset? DateCreated { get; set; }
        [Display(Name = "Date Updated")]
        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public DateTimeOffset? DateUpdated { get; set; }
        [Display(Name = "User Created")]
        public string UserCreated { get; set; }
        [Display(Name = "User Updated")]
        public string UserUpdated { get; set; }
    }
}

Attendance/Attendance/ViewModels/Locations/EditLocationVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Attendance.ViewModels
{
    public class EditLocationVM
    {
        public int Id { get; set; }

        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

    }
}

Attendance/Attendance/ViewModels/Locations/LocationListVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Attendance.ViewModels
{
    public class LocationListVM
    {
        public int Id { get; set; }
        [Display(Name = "Location")]
        [Required]
        [StringLength(500)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Display(Name = "Date Created")]
        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public DateTimeOffset? DateCreated { get; set; }
        [Display(Name = "Date Updated")]
        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]
        public DateTimeOffset? DateUpdated { get; set; }
        [Display(Name = "User Created")]
        public string UserCreated { get; set; }
        [Display(Name = "User Updated")]
        public string UserUpdated { get; set; }
    }
}

Attendance/Attendance/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Attendance.DBContext;
using Attendance.Models;
using Attendance.Services;
using Attendance.ViewModels;


namespace Attendance.Controllers
{
    public class LocationsController : Controller
    {
        //private AttendanceOracleDbContext db = new AttendanceOracleDbContext();
        private LocationService _locationService;

        public LocationsController()
        {
            this._locationService = new LocationService();
        }

        // GET: Location
        public async Task<ActionResult> Index()
        {
            IEnumerable<Location> allLocations = await _locationService.GetAll();
            List<LocationListVM> allLocationslist = new List<LocationListVM>();

            foreach (var loc in allLocations)
            {
                LocationListVM locationVM = new LocationListVM()
                {
                Id = loc.Id,
                Name = loc.Name,
                Description = loc.Description,
                DateCreated = loc.DateCreated,
                UserCreated = loc.UserCreated,
                DateUpdated = loc.DateUpdated,
                UserUpdated = loc.UserUpdated
                };
                allLocationslist.Add(locationVM);
            }

            return View(allLocationslist);
        }

        // GET: Location/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            DetailsLocationVM details = new DetailsLocationVM();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Location location = await db.Location.FindAsync(id);
            Location location = await _locationService.Get(id.Value);

            if (location == null)
            {
                return HttpNotFound();
            }
            details.Name = location.Name;
            details.Description = location.Description;
            details.DateCreated = location.DateCreated;
            details.UserCreated = location.UserCreated;
            details.DateUpdated = location.DateUpdated;
            details.UserUpdated = location.UserUpdated;
            return View(details);
        }

        // GET: Location/Create
        [HttpGet]
        public ActionResult Create()
        {
            CreateLocationVM model = new CreateLocationVM();
            return View(model);
        }

        // POST: Location/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateLocationVM model)
        {
            if (ModelState.IsValid)
            {
                Location newLocation = new Location()
                {

                    Name = model.Name,
                    Description = model.Description,
                    DateCreated = DateTimeOffset.Now,
                    UserCreated = ""
                                    };
                await _locationService.Create(newLocation);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Location/Edit/5
        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            EditLocationVM model = new EditLocationVM();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await _locationService.Get(id.Value);
            if (location == null)
            {
                return HttpNotFound();
            }
            model.Description = location.Description;
            model.Name = location.Name;
            model.Id = location.Id;
            return View(model);
        }

        // POST: Location/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditLocationVM model, int? id)
        {

            if (ModelState.IsValid)
            {
               Location existingLocation = await _locationService.Get(id.Value);
                if (existingLocation != null)
                {
                    existingLocation.Name = model.Name;
                    existingLocation.Description = model.Description;
                    existingLocation.DateUpdated = DateTimeOffset.Now;
                    await _locationService.Update(existingLocation);
                }
                else
                {
                    return HttpNotFound();
                }
                await _locationService.Update(existingLocation);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Location/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            DeleteLocationVM delete = new DeleteLocationVM();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = await _locationService.Get(id.Value);
            if (location == null)
            {
                return HttpNotFound();
            }
            delete.Name = location.Name;
            delete.Description = location.Description;
            delete.DateCreated = location.DateCreated;
            delete.UserCreated = location.UserCreated;
            delete.DateUpdated = location.DateUpdated;
            delete.UserUpdated = location.UserUpdated;
            return View(delete);
        }

        // POST: Location/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _locationService.Delete(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _locationService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Attendance/Attendance/Views/Locations/Create.cshtml
@model Attendance.ViewModels.CreateLocationVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Locations", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    <h4>Locations</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control"} })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", rows = "10" } })

            @*<input type="text" id="Description" name="Description" />*@

            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Attendance/Attendance/Views/Locations/Delete.cshtml
@model Attendance.ViewModels.DeleteLocationVM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Locations</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserUpdated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Attendance/Attendance/Views/Locations/Details.cshtml
@model Attendance.ViewModels.DetailsLocationVM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Locations</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserUpdated)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Attendance/Attendance/Views/Locations/Edit.cshtml
@model Attendance.ViewModels.EditLocationVM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Locations", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Locations</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control"  } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", rows = "10" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Attendance/Attendance/Views/Locations/Index.cshtml
@model IEnumerable<Attendance.ViewModels.LocationListVM>

@{
    ViewBag.Title = "Locations";
}

<h2>Locations</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
           
            <th></th>
        </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description, new { @class = "control-label col-md-6" })
                </td>
               
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>

</table>

@section styles
{
    @Styles.Render("~/Content/locations/locations.css")
}